services:
  gitlab:
    image: gitlab/gitlab-ce:18.7.0-ce.0
    restart: unless-stopped
    hostname: gitlab
    environment:
      GITLAB_ROOT_PASSWORD: "${GITLAB_ROOT_PASSWORD:-changeme123}"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
    ports:
      - "8081:80"
      - "2222:22"
    networks:
      - ci-network

  teamcity:
    image: jetbrains/teamcity-server:2023.05
    restart: unless-stopped
    environment:
      TEAMCITY_SERVER_MEM_OPTS: "-Xmx1g"
    ports:
      - "8111:8111"
    networks:
      - ci-network

  bootstrap:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    depends_on:
      - gitlab
      - teamcity
    env_file:
      - .env
    volumes:
      - ./src:/app:ro
      - ./data:/data:ro
    working_dir: /app
    entrypoint: ["/bin/sh", "-c", "dotnet run"]
    networks:
      - ci-network

networks:
  ci-network:
    driver: bridge
