#!/bin/bash

set -eou pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

pushd "$SCRIPT_DIR/.." >/dev/null

# Remove stale tokens from .env to prevent bootstrap failures
# These will be regenerated by the token-generator containers
if [ -f .env ]; then
  sed -i '/^GITLAB_TOKEN=/d' .env
  sed -i '/^TEAMCITY_TOKEN=/d' .env
  echo "Cleaned stale tokens from .env"
fi

docker compose -f cilab-compose.yaml down -v
docker compose -f cilab-compose.yaml up

popd